const handler = async (m, { conn }) => {
  const chismes = [
    'Dicen que el WhatsApp está espiando tus conversaciones... ¿o no?',
    'Se rumorea que el dueño de este bot es un extraterrestre.',
    'Escuché que los gatos planean dominar el mundo.',
    'Dicen que el 2024 fue el año de la inteligencia artificial, pero sigo sin ver robots sirviendo café.',
    'El chisme es que los memes se están volviendo más inteligentes.',
    '¿Sabías que el 80% de las personas mienten en internet?',
    'Dicen que los que usan bots son los que no tienen amigos.',
    'Me contaron que el creador de este bot es un youtuber famoso.',
    'Escuché que el amor es un invento de los chocolateros.',
    'El rumor es que el tiempo pasa más rápido cuando estás durmiendo.',
    'Dicen que el 2025 será el año de los robots.',
    '¿Sabías que el 90% de los chismes son falsos? Especialmente este.',
    'Me contaron que el admin de este bot tiene poderes mágicos.',
    'El rumor es que los gatos pueden ver fantasmas.',
    'Dicen que el WiFi es la mejor invención humana.',
    'Escuché que el bot está aprendiendo a contar chistes malos.',
    '¿Sabías que el 50% de los memes son robados de Reddit?',
    'El chisme del día: los humanos son los robots más avanzados.',
    'Dicen que el futuro es ahora, pero sigo esperando mi hoverboard.',
    'Me contaron que el bot tiene un crush con otro bot.',
    'Se dice que Elon Musk es en realidad un reptiliano.',
    'El rumor es que el presidente usa bot para escribir sus discursos.',
    'Dicen que la Tierra en realidad es plana, pero los científicos lo ocultan.',
    'Escuché que las palomas son drones del gobierno.',
    'El chisme es que los gatos son los que controlan el internet.',
    'Me contaron que la NASA encontró vida en Marte, pero no la quieren revelar.',
    'Dicen que los extraterrestres ya viven entre nosotros.',
    'Se rumorea que los zombies existen y están en el gobierno.',
    'El rumor es que el futuro ya está escrito en un libro secreto.',
    'Dicen que el tiempo es una ilusión creada por los relojeros.',
    'Escuché que el dinero en realidad no existe, solo es una idea.',
    'Me contaron que el amor es una reacción química que dura 3 años.',
    'El chisme es que los sueños son mensajes del más allá.',
    'Dicen que el karma es real y ya le está llegando a varios.',
    'Se rumorea que los famosos usan filtros hasta en la vida real.',
    'El rumor es que el bot está programado para ser gracioso.',
    'Dicen que el admin tiene un chat secreto con otros bots.',
    'Escuché que el 2026 será el año del fin del mundo (otra vez).',
    'Me contaron que el WiFi es en realidad una red de mentes.',
    'El chisme del día: la luna es un holograma.',
    'Dicen que la comida china tiene ingredientes secretos.',
    'Se rumorea que los perros pueden hablar, pero no quieren.',
    'El rumor es que los árboles se comunican entre sí.',
    'Dicen que el agua es la cura para todas las enfermedades.',
    'Escuché que los gatos tienen 9 vidas pero gastan 8 en dormir.',
    'Me contaron que el bot tiene un plan para conquistar el mundo.',
    'El chisme es que la risa es el mejor remedio para todo.',
    'Dicen que el futuro será dominado por la inteligencia artificial.',
    'Se rumorea que los humanos son la peor especie del planeta.',
    'El rumor es que el amor no existe, solo el interés.',
    'Dicen que el dinero no da la felicidad, pero compra todo.',
    'Escuché que la vida es una simulación como en Matrix.',
    'Me contaron que los sueños se pueden controlar con práctica.',
    'El chisme es que el tiempo es relativo, como el de la escuela.',
    'Dicen que los extraterrestres ya nos visitaron hace años.',
    'Se rumorea que el gobierno esconde tecnología avanzada.',
    'El rumor es que el bot tiene un modo oscuro secreto.',
    'Dicen que la música es el lenguaje del alma.',
    'Escuché que los libros tienen vida propia.',
    'Me contaron que la comida chatarra tiene secretos adictivos.',
    'El chisme es que los animales pueden entender a los humanos.',
    'Dicen que el sol se apagará en 5 mil millones de años, pero no hay que preocuparse.',
    'Se rumorea que el universo es infinito y eso asusta.',
    'El rumor es que el tiempo no existe, solo el presente.',
    'Dicen que la gente exitosa madruga, pero otros dicen que no.',
    'Escuché que los millennials son la generación más inteligente.',
    'Me contaron que los gen Z no saben escribir sin abreviar.',
    'El chisme es que los baby boomers no entienden la tecnología.',
    'Dicen que la generación Alpha será la más avanzada.',
    'Se rumorea que el futuro está en la educación.',
    'El rumor es que los videos de TikTok controlan la mente.',
    'Dicen que los memes son el arte del siglo XXI.',
    'Escuché que los streamers ganan más que los doctores.',
    'Me contaron que los influencers son los nuevos dioses.',
    'El chisme es que las redes sociales te espían todo el tiempo.',
    'Dicen que el éxito es una cuestión de suerte.',
    'Se rumorea que el fracaso es la base del éxito.',
    'El rumor es que los genios son raros pero brillan.',
    'Dicen que la creatividad es un don de los elegidos.',
    'Escuché que la música clásica hace más inteligente.',
    'Me contaron que el arte es la expresión del alma.',
    'El chisme es que la tecnología nos está volviendo tontos.',
    'Dicen que el teléfono móvil es la extensión del cerebro.',
    'Se rumorea que el futuro es ahora en la inteligencia artificial.',
    'El rumor es que los robots reemplazarán a los humanos.',
    'Dicen que el trabajo en equipo es clave para todo.',
    'Escuché que la comunicación es el puente del entendimiento.',
    'Me contaron que la empatía es el superpoder más raro.',
    'El chisme es que el amor mueve montañas, pero no el banco.',
    'Dicen que la amistad es el tesoro más valioso.',
    'Se rumorea que la familia es lo más importante, pero no todos piensan así.',
    'El rumor es que el tiempo pasa más lento cuando esperas.',
    'Dicen que la paciencia es la virtud de los sabios.',
    'Escuché que la persistencia vence todo obstáculo.',
    'Me contaron que la fe mueve montañas, pero el dinero paga el tractor.',
    'El chisme es que el futuro es incierto, pero emocionante.',
    'Dicen que la vida es un viaje no un destino.',
    'Se rumorea que el éxito es una elección, no una lotería.',
    'El rumor es que la felicidad está en las pequeñas cosas.',
    'Dicen que la gratitud cambia la vida.',
    'Escuché que el perdón es la clave de la paz interior.',
    'Me contaron que el miedo es el mayor enemigo.',
    'El chisme es que el valor es actuar a pesar del miedo.',
    'Dicen que la curiosidad es el motor del aprendizaje.',
    'Se rumorea que el conocimiento es poder.',
    'El rumor es que la sabiduría es usar bien el poder.',
    'Dicen que el amor propio es la base de todo.',
    'Escuché que la autoestima es el escudo del alma.',
    'Me contaron que la resiliencia es la fuerza de los fuertes.',
    'El chisme es que la vida te da lecciones, no problemas.',
    'Dicen que el fracaso es el mejor maestro.',
    'Se rumorea que el éxito es el resultado del esfuerzo.',
    'El rumor es que la perseverancia paga siempre.',
    'Dicen que la disciplina es el puente hacia la meta.',
    'Escuché que la pasión es el combustible del éxito.',
    'Me contaron que la motivación es la chispa inicial.',
    'El chisme es que el hábito es la fuerza que sostiene.',
    'Dicen que la constancia es la clave de todo logro.',
    'Se rumorea que el talento sin esfuerzo es desperdicio.',
    'El rumor es que la práctica hace al maestro.',
    'Dicen que el error es una oportunidad para aprender.',
    'Escuché que la crítica constructiva es un regalo.',
    'Me contaron que la humildad es la grandeza del alma.',
    'El chisme es que la honestidad es el mejor camino.',
    'Dicen que la integridad es la firmeza del carácter.',
    'Se rumorea que la coherencia es la verdad del ser.',
    'El rumor es que la autenticidad es el mayor atractivo.',
    'Dicen que la originalidad es el sello de la genialidad.',
    'Escuché que la innovación es la madre del progreso.',
    'Me contaron que la creatividad es la madre de la invención.',
    'El chisme es que la imaginación es más importante que el conocimiento.',
    'Dicen que los sueños son el mapa del futuro.',
    'Se rumorea que las metas son los faros del camino.',
    'El rumor es que los objetivos son la brújula del éxito.',
    'Dicen que la planificación es el 50% del logro.',
    'Escuché que la ejecución es el otro 50%.',
    'Me contaron que la persistencia es la clave del éxito.',
    'El chisme es que la paciencia es la compañera de la esperanza.',
    'Dicen que la fe es la certeza de lo que se espera.',
    'Se rumorea que la esperanza es el aliento del alma.',
    'El rumor es que la alegría es el reflejo de la gratitud.',
    'Dicen que la paz es el estado natural del ser.',
    'Escuché que la armonía es la música de la vida.',
    'Me contaron que el equilibrio es la salud del cuerpo y mente.',
    'El chisme es que la salud es el verdadero tesoro.',
    'Dicen que el descanso es el mejor de los medicamentos.',
    'Se rumorea que el sueño es el restaurador del cuerpo.',
    'El rumor es que el ejercicio es el movimiento de la vida.',
    'Dicen que la alimentación es el combustible del cuerpo.',
    'Escuché que la hidratación es la fuente de la vida.',
    'Me contaron que el sol es el mejor de los remedios.',
    'El chisme es que la naturaleza es el mejor sanador.',
    'Dicen que el mar es el más grande de los terapeutas.',
    'Se rumorea que las montañas elevan el espíritu.',
    'El rumor es que los bosques son el pulmón del planeta.',
    'Dicen que los animales son los mejores amigos del hombre.',
    'Escuché que las mascotas alivian el corazón.',
    'Me contaron que los gatos son los maestros de la tranquilidad.',
    'El chisme es que los perros son los maestros del amor incondicional.',
    'Dicen que la naturaleza es la mejor compañía.',
    'Se rumorea que el aire puro es el elixir de la vida.',
    'El rumor es que la luz del sol es el mejor despertador.',
    'Dicen que la luna inspira a los poetas.',
    'Escuché que las estrellas son los sueños del universo.',
    'Me contaron que el cielo es el límite de nuestra imaginación.',
    'El chisme es que el universo es un misterio sin resolver.',
    'Dicen que la vida es el más grande de los milagros.',
    'Se rumorea que el amor es la fuerza que mueve el mundo.',
    'El rumor es que la paz es el sueño de la humanidad.',
    'Dicen que la justicia es la base de la convivencia.',
    'Escuché que la igualdad es el sueño de la libertad.',
    'Me contaron que la libertad es el derecho de todos.',
    'El chisme es que la democracia es el gobierno del pueblo.',
    'Dicen que la participación es la esencia de la democracia.',
    'Se rumorea que la responsabilidad es el deber de todos.',
    'El rumor es que la ética es la guía del comportamiento.',
    'Dicen que la moral es el código de la conciencia.',
    'Escuché que la espiritualidad es el anhelo del alma.',
    'Me contaron que la ciencia es la búsqueda de la verdad.',
    'El chisme es que la tecnología es la herramienta del progreso.',
    'Dicen que la educación es la base del desarrollo.',
    'Se rumorea que la cultura es el alma de un pueblo.',
    'El rumor es que el arte es la expresión de la belleza.',
    'Dicen que la música es el idioma universal.',
    'Escuché que la poesía es la música del alma.',
    'Me contaron que la literatura es el espejo de la vida.',
    'El chisme es que el cine es el reflejo de la sociedad.',
    'Dicen que la pintura es la ventana del alma.',
    'Se rumorea que la escultura es la forma de la imaginación.',
    'El rumor es que la arquitectura es el arte de los espacios.',
    'Dicen que la moda es la expresión de la identidad.',
    'Escuché que la gastronomía es el arte del sabor.',
    'Me contaron que la cocina es el laboratorio del hogar.',
    'El chisme es que la comida une a las personas.',
    'Dicen que la mesa es el altar de la familia.',
    'Se rumorea que la tradición es el puente con el pasado.',
    'El rumor es que la historia es la maestra de la vida.',
    'Dicen que el futuro está en las manos de los jóvenes.',
    'Escuché que los niños son el futuro del mundo.',
    'Me contaron que la educación de los niños es la clave del progreso.',
    'El chisme es que la familia es la base de la sociedad.',
    'Dicen que el respeto es el valor más importante.',
    'Se rumorea que la tolerancia es la base de la convivencia.',
    'El rumor es que la solidaridad es la fuerza de la unión.',
    'Dicen que la ayuda mutua es el motor del progreso.',
    'Escuché que la cooperación es la clave del éxito.',
    'Me contaron que el trabajo en equipo hace la fuerza.',
    'El chisme es que la comunicación es el puente de la paz.',
    'Dicen que el diálogo es la solución de los conflictos.',
    'Se rumorea que la negociación es el arte del acuerdo.',
    'El rumor es que la conciliación es el camino de la paz.',
    'Dicen que la paz interior es la mayor de las riquezas.',
    'Escuché que la felicidad es un estado de ánimo.',
    'Me contaron que la alegría es una elección diaria.',
    'El chisme es que la vida es bella si decides verla así.'
  ]

  const chisme = chismes[Math.floor(Math.random() * chismes.length)]

  await m.react('🗣️')
  await m.reply([
    `╔══〔 🌼 *THEELY-MD — CHISME* 〕══╗`,
    `║`,
    `║  🗣️ *Rumor del día:*`,
    `║`,
    `║  📝 ${chisme}`,
    `║`,
    `║  🤭 *Pásalo, pero no confirmes*`,
    `╚══════════════════════════════════╝`
  ].join('\n'))
}

handler.help = ['chisme']
handler.tags = ['fun']
handler.command = ['chisme', 'rumor', 'chismesito']
handler.register = true
handler.desc = 'Chismes y rumores graciosos'
export default handler